name: w_builder
description: A powerful CLI tool for w.ever team to architect Flutter features and boost productivity.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.0.3
  infinite_scroll_pagination: ^5.1.0
  mustache_template: ^2.0.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  yaml: ^3.1.3
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
