name: w_builder
description: A powerful CLI tool for w.ever team to architect Flutter features and boost productivity.
version: 2.0.2
homepage: https://github.com/Alaa-shibany/w_builder
repository: https://github.com/Alaa-shibany/w_builder

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  infinite_scroll_pagination: ^5.1.0
  mustache_template: ^2.0.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  yaml: ^3.1.3
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  lints: ^5.0.0
  test: ^1.24.0

executables:
  w_builder:
