name: w_builder
description: A powerful CLI tool for w.ever team to architect Flutter features and boost productivity.
version: 2.0.0
homepage: https://github.com/Alaa-shibany/w_builder
repository: https://github.com/Alaa-shibany/w_builder

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  get_it: ^8.0.3
  mustache_template: ^2.0.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  yaml: ^3.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  w_builder:
